### PR TITLE
Fix remote add command comment

### PR DESCRIPTION
**Pull request by AustinScola**
Fix the comment for adding a remote repository.

### CODE REVIEW

**Comment by AustinScola** [comment]
Address Issue #21

**Comment by webknjaz** [comment]
Thanks!

**Comment by AustinScola** [comment]
No problem! This is a cool GitHub App that you have created. Out of curiosity, what percentage of the time have you observed that the patchbacks apply cleanly vs. require manual conflict resolution?

**Comment by webknjaz** [comment]
The idea actually comes from what CPython folks did for their project (that is a user account-based bot, not a GitHub App, though).

I don't have the stats. I think @ansible-collections is the biggest consumer, maybe @felixfontein could answer the question about the clean cherry-picks.

In general, this depends on how different the target branch is compared to the main are + the order of backporting the subsequent PRs that edit the same file.

**Comment by AustinScola** [comment]
> The idea actually comes from what CPython folks did for their project (that is a user account-based bot, not a GitHub App, though).

Ahh, cool. I wonder if that was made before GitHub Apps were around. I also saw this is using `gidgethub` which I think was spawned out of CPython as well.

> In general, this depends on how different the target branch is compared to the main are + the order of backporting the subsequent PRs that edit the same file.

Interesting, I hadn't considered the case that the ordering might not be the same.

**Comment by felixfontein** [comment]
> I don't have the stats. I think @ansible-collections is the biggest consumer, maybe @felixfontein could answer the question about the clean cherry-picks.

It depends a lot on the repository I'd say, and how much activity happens to parts of it, and how much of that activity is backported and how much not (breaking changes vs. features vs. bugfixes). In case of community.general, I'd say that it works most of the time. There are some situations where I'm pretty sure it probably won't work and I'm trying it anyway, to safe some manual work in case it does work (sometimes git is more clever than expected).

**Comment by AustinScola** [comment]
Thanks for the insights @felixfontein.

**Pull request merged**
